version: "3"

networks:
    apibook:
        driver: bridge

services:
    mongo:
        image: mongo
        container_name: apibook-mongo
        ports:
            - 27017:27017
        volumes:
            - ./database/mongo:/data/db
        networks:
            - apibook

    node:
        build: ./
        container_name: apibook-node
        ports:
            - 14240:14240
            - 16240:16240
        volumes:
            - ./:/app
        networks:
            - apibook
        depends_on:
            - mongo
        tty: true
