version: "3"

networks:
    apibook:
      driver: bridge

services:

    mongo:
      image: mongo
      container_name: apibook-mongo
      ports:
        - 14241:27017
      volumes:
        - ./database/mongo:/data/db
      networks:
        - apibook

    node:
      build: ./backend
      container_name: apibook-node
      ports:
        - 14240:14240
      volumes:
        - ./backend:/app
      networks:
        - apibook
      depends_on:
        - mongo
      tty: true

